version: "3.6"
services:
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/opt/client
  database:
    build: ./database
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=database
      - DB_PORT=27017
    volumes:
      - ./server:/opt/server
    depends_on:
      - database
volumes:
  db:
